# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7adb651d649e8a5c7d46b544ebbcc393fdaa3f93d877ab6f78bdc0d32bac04b03d7f81857bc32c151ca59807f317fc077baa43f7b7a657788cd85febe7c2a1a

test:
  secret_key_base: 28b77f500cbc64c0f1e530c63df370e2a8284c399da357bf52fc94530fc6d2cd335536e32865f58a5a000f8c9c471fc1ca8954859d79f66b18e206311fd5d2c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
